import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { api } from "~/utils/api";
import { Header } from "~/components/Header/Header";
import { useState } from "react";
import { Section } from "@prisma/client";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Take Note</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Content />
      </main>
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const { data: sessionData } = useSession();

  const [selectedSection, setSelectedSection] = useState<Section | null>(null);

  const { data: sections, refetch: refetchSections } = api.section.getAll.useQuery(
      undefined,
      {
        enabled: sessionData?.user !== undefined,
        onSuccess: (data) => {
          setSelectedSection(selectedSection ?? data[0] ?? null);
        }
      }
  );

  const createSection = api.section.create.useMutation({
    onSuccess: () => {
      void refetchSections();
    }
  });

  return (
    <div>
      <ul>
        {sections?.map((section) => (
          <li>
            <a
              href='#'
              onClick={(e) => {
                e.preventDefault();
                setSelectedSection(section);
              }}
            >
              {section.title}
            </a>
          </li>
        ))}
      </ul>
      <input
        type="text"
        placeholder="New Section"
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            createSection.mutate({
              title: e.currentTarget.value,
            });

            e.currentTarget.value = "";
          }
        }}
      />
    </div>
  );
}
