import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { Header } from "~/components/Header/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Take Note</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Content />
      </main>
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: sections, refetch: refetchSections } = api.section.getAll.useQuery(
      undefined,
      {
          enabled: sessionData?.user !== undefined,
      }
  );

  return <div>{JSON.stringify(sections)}</div>;
}
